/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MyJobsRouteImport } from './routes/my-jobs'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAffiliatesRouteImport } from './routes/admin.affiliates'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as EnterpriseOwnerIdRouteImport } from './routes/enterprise.$ownerId'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as WorkersWorkerIdRouteImport } from './routes/workers.$workerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsRoute = MyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const EnterpriseOwnerIdRoute = EnterpriseOwnerIdRouteImport.update({
  id: '/enterprise/$ownerId',
  path: '/enterprise/$ownerId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersWorkerIdRoute = WorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/inbox': typeof InboxRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/enterprise/$ownerId': typeof EnterpriseOwnerIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/inbox': typeof InboxRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/enterprise/$ownerId': typeof EnterpriseOwnerIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/workers': typeof WorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/inbox': typeof InboxRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/enterprise/$ownerId': typeof EnterpriseOwnerIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/inbox'
    | '/my-jobs'
    | '/post-job'
    | '/admin/affiliates'
    | '/admin/finance'
    | '/admin/moderation'
    | '/enterprise/$ownerId'
    | '/jobs/$jobId'
    | '/workers/$workerId'
    | '/admin/'
    | '/jobs/'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/inbox'
    | '/my-jobs'
    | '/post-job'
    | '/admin/affiliates'
    | '/admin/finance'
    | '/admin/moderation'
    | '/enterprise/$ownerId'
    | '/jobs/$jobId'
    | '/workers/$workerId'
    | '/admin'
    | '/jobs'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/inbox'
    | '/my-jobs'
    | '/post-job'
    | '/admin/affiliates'
    | '/admin/finance'
    | '/admin/moderation'
    | '/enterprise/$ownerId'
    | '/jobs/$jobId'
    | '/workers/$workerId'
    | '/admin/'
    | '/jobs/'
    | '/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  InboxRoute: typeof InboxRoute
  MyJobsRoute: typeof MyJobsRoute
  PostJobRoute: typeof PostJobRoute
  EnterpriseOwnerIdRoute: typeof EnterpriseOwnerIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  WorkersWorkerIdRoute: typeof WorkersWorkerIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs': {
      id: '/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof MyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/enterprise/$ownerId': {
      id: '/enterprise/$ownerId'
      path: '/enterprise/$ownerId'
      fullPath: '/enterprise/$ownerId'
      preLoaderRoute: typeof EnterpriseOwnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$workerId': {
      id: '/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  InboxRoute: InboxRoute,
  MyJobsRoute: MyJobsRoute,
  PostJobRoute: PostJobRoute,
  EnterpriseOwnerIdRoute: EnterpriseOwnerIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  WorkersWorkerIdRoute: WorkersWorkerIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
